### ISSUE TITLE
AclExtras verify throws exception

### ISSUE THREAD

**Issue by boindil** [cakephp/acl#52]
```bin/cake acl_extras verify aro```
results in
```
Exception: Unknown method "verify" in [/pathToCake/vendor/cakephp/cakephp/src/ORM/Table.php, line 1719]
2015-02-07 22:08:16 Error: [BadMethodCallException] Unknown method "verify"
Stack Trace:
#0 /pathToCake/plugins/Acl/src/AclExtras.php(337): Cake\ORM\Table->__call('verify', Array)
#1 /pathToCake/plugins/Acl/src/AclExtras.php(337): Acl\Model\Table\ArosTable->verify()
#2 /pathToCake/plugins/Acl/src/Shell/AclExtrasShell.php(159): Acl\AclExtras->verify()
#3 [internal function]: Acl\Shell\AclExtrasShell->verify('aro')
#4 /pathToCake/vendor/cakephp/cakephp/src/Console/Shell.php(376): call_user_func_array(Array, Array)
#5 /pathToCake/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(200): Cake\Console\Shell->runCommand(Array, true)
#6 /pathToCake/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(171): Cake\Console\ShellDispatcher->_dispatch()
#7 /pathToCake/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(122): Cake\Console\ShellDispatcher->dispatch()
#8 /pathToCake/bin/cake.php(20): Cake\Console\ShellDispatcher::run(Array)
#9 {main}
```

**Comment by sarrala** [comment]
Related issue #47 and fix #62

**Comment by markstory** [comment]
Fixed in #62

**Comment by boindil** [comment]
Not fixed. Tried using clean checkout.

Still the same error. ```ArosTable->verify()``` is called while this method does not exist.

**Comment by markstory** [comment]
Oh yeah, there is no verify method anymore. I'll remove the AclExtras command as it will never work.
